### ISSUE TITLE
Can' t save an array of chosen bubbles

### ISSUE THREAD

**Issue by romanrakhlin** [UOL-edtech/UEBubblePicker#1]
How i can do it?

**Comment by iurichiba** [comment]
I'm not sure I follow. Can you explain what exactly you're trying to do?

Just in case that's what you're having trouble with: you can get the selected bubbles from the container using `.selectedBubbles` -- from there, you can get their tags or any other information you need from them.

**Comment by iurichiba** [comment]
This issue has been inactive for 2 weeks. I'm closing it for now.
